builds:
  - id: darwin-amd64
    main: ./cmd/afrog/
    binary: afrog
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: linux-amd64
    main: ./cmd/afrog/
    binary: afrog
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/opt/vc/lib/pkgconfig:/sysroot/linux/amd64/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/amd64/usr/lib/pkgconfig:/sysroot/linux/amd64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: afrog
    builds:
      - darwin-amd64
      - linux-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: zan8in
    name: afrog
  prerelease: auto
  draft: false