project_name: afrog
homepage: https://github.com/zan8in/afrog
description: A Security Tool for Bug Bounty, Pentest and Red Teaming.

builds:
  - id: linux
    os:
      - linux
    arch:
      - amd64
      - arm64
    goos: linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    go_build_flags:
      - -tags=main
      - -ldflags='-s -w'
    main:
      goos: linux
      goarch: amd64

  - id: windows
    os:
      - windows
    arch:
      - amd64
    goos: windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    go_build_flags:
      - -tags=main
      - -ldflags='-s -w'
    main:
      goos: windows
      goarch: amd64

# Add more platforms as needed...

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

tarball:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz'
  format: tar.gz

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.zip'
    format: zip
    files:
      - dist/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}/*

release:
  github:
    owner: zan8in
    name: afrog
  # Add other release targets as needed...

signs:
  - artifacts:
      - checksums.txt
      - '*.tar.gz'
      - '*.zip'
      - '*.gz'
      - '*.bz2'
    cmd: gpg --output '{{ .ArtifactName }}.sig' --detach-sig '{{ .ArtifactName }}'
