before:
  hooks:
    - go mod tidy
builds:
  - id: darwin-amd64
    main: ./cmd/afrog/
    binary: afrog
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1  # 启用CGO
      # - CC=o64-clang
      # - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  
archives:
  - id: afrog
    builds:
      - darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: zan8in
    name: afrog
  prerelease: auto
  draft: false